site_name: The PEON Project 
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default 
      toggle:
        icon: material/toggle-switch
        name: dark mode    
      primary: green
      accent: gray
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline 
        name: light mode
      primary: green 
      accent: black
  icon:
    repo:
      fontawesome/brands/github

extra:
  social:
    - icon: simple/kofi
      link: https://ko-fi.com/umlatt
    - icon: fontawesome/brands/discord
      link: https://discord.gg/KJFVyayH8g
    - icon: fontawesome/brands/github
      link: https://github.com/the-peon-project
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/repository/docker/umlatt/peon.orc/general

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
repo_url: https://github.com/the-peon-project
copyright: |
  &copy; 2023 <a href="https://github.com/the-peon-project"  target="_blank" rel="noopener">The PEON Project</a>